services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: 'application'
      POSTGRES_PASSWORD: 'superSecretPassw0rd'
      POSTGRES_DB: 'fleet'

    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend/
    command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"