services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: 'application'
      POSTGRES_PASSWORD: 'superSecretPassw0rd'
      POSTGRES_DB: 'fleet'

